name: Frontend CI

on:
    push:
        branches:
            - main
        paths:
            - "frontend/**"

jobs:
    build-and-test:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"
            - name: Install pnpm
              run: npm install -g pnpm
            - name: Install dependencies
              working-directory: frontend
              run: pnpm install
            - name: Run tests
              working-directory: frontend
              run: pnpm test
            - name: Build
              working-directory: frontend
              run: pnpm build
